In [1]:
import torch
from qtorch import FloatingPoint, FixedPoint
from qtorch.quant import Quantizer, quantizer

# Define a quantizer

# Quantize a tensor
tensor = torch.randn(5, 5)
print(tensor)

tensor([[ 0.7423, -1.3774,  0.4534, -0.6612,  0.1877],
        [-0.3408, -0.2468, -0.5433, -0.3291,  0.1265],
        [ 1.4335,  1.4212,  1.3682, -1.8930,  1.0162],
        [ 2.2481, -0.2917,  0.9392,  0.3962,  1.4399],
        [-0.6950,  0.4473,  0.0480,  0.9110, -1.1612]])


In [13]:
# Define a quantizer
# number = FloatingPoint(3, 0)
number = FixedPoint(4, 3)

quantizer = Quantizer(number)

qtensor = quantizer(tensor)
print(qtensor)
print(qtensor.unique())


tensor([[ 0.7500, -1.0000,  0.3750, -0.6250,  0.2500],
        [-0.3750, -0.2500, -0.5000, -0.3750,  0.1250],
        [ 0.8750,  0.8750,  0.8750, -1.0000,  0.8750],
        [ 0.8750, -0.3750,  0.8750,  0.3750,  0.8750],
        [-0.6250,  0.5000,  0.1250,  0.8750, -1.0000]])
tensor([-1.0000, -0.6250, -0.5000, -0.3750, -0.2500,  0.1250,  0.2500,  0.3750,
         0.5000,  0.7500,  0.8750])


In [3]:
quantized_tensor = quantizer(tensor)

print(quantized_tensor)

tensor([[ 2.0000, -0.2500, -0.2500,  0.0000,  0.2500],
        [-0.5000,  2.0000, -0.5000,  1.0000, -2.0000],
        [-1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
        [-0.5000,  2.0000,  2.0000,  0.2500,  2.0000],
        [ 0.2500,  4.0000,  4.0000,  1.0000, -2.0000]])


In [6]:
def find_nearest_pow2(x: torch.Tensor):
    # can be negative power
    return torch.sign(x) * torch.pow(2, torch.round(torch.log2(torch.abs(x))))


In [7]:
find_nearest_pow2(tensor)

tensor([[ 1.0000, -0.5000, -0.5000,  0.0078,  0.2500],
        [-0.5000,  2.0000, -1.0000,  0.5000, -2.0000],
        [-1.0000,  0.5000,  1.0000,  1.0000,  1.0000],
        [-0.5000,  2.0000,  2.0000,  0.2500,  2.0000],
        [ 0.2500,  4.0000,  4.0000,  1.0000, -2.0000]])