In [2]:
import torch
from qtorch import FloatingPoint
from qtorch.quant import Quantizer, quantizer

# Define a quantizer
number = FloatingPoint(3, 0)

# Define a quantizer
quantizer = Quantizer(number)

# Quantize a tensor
tensor = torch.randn(5, 5)
print(tensor)

tensor([[ 1.1018, -0.4849, -0.3823,  0.0072,  0.3023],
        [-0.5042,  2.1079, -0.7276,  0.6558, -1.7717],
        [-0.9293,  0.6492,  0.8897,  0.9741,  0.9357],
        [-0.5555,  1.7011,  1.8253,  0.3090,  1.9695],
        [ 0.1777,  2.9094,  3.8829,  1.1143, -1.7042]])


In [3]:
quantized_tensor = quantizer(tensor)

print(quantized_tensor)

tensor([[ 2.0000, -0.2500, -0.2500,  0.0000,  0.2500],
        [-0.5000,  2.0000, -0.5000,  1.0000, -2.0000],
        [-1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
        [-0.5000,  2.0000,  2.0000,  0.2500,  2.0000],
        [ 0.2500,  4.0000,  4.0000,  1.0000, -2.0000]])


In [6]:
def find_nearest_pow2(x: torch.Tensor):
    # can be negative power
    return torch.sign(x) * torch.pow(2, torch.round(torch.log2(torch.abs(x))))


In [7]:
find_nearest_pow2(tensor)

tensor([[ 1.0000, -0.5000, -0.5000,  0.0078,  0.2500],
        [-0.5000,  2.0000, -1.0000,  0.5000, -2.0000],
        [-1.0000,  0.5000,  1.0000,  1.0000,  1.0000],
        [-0.5000,  2.0000,  2.0000,  0.2500,  2.0000],
        [ 0.2500,  4.0000,  4.0000,  1.0000, -2.0000]])